--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Sandertv/BlockPets
branches:
- master
projects:
  BlockPets:
    path: ""
    libs:
      - src: Falkirks/spoondetecctor/spoondetector
        version: ^0
...
